version: "3.7"
services:
  app:
    build:
      args:
        user: localuser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app-image
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - /var/www/node_modules
      - /var/www/public/build
    networks:
      - app-network

  db:
    image: mysql:8.2
    container_name: app-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: docker-preset-db
      MYSQL_ROOT_PASSWORD: testpw
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network

  nginx:
    image: nginx:1.17-alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
